from __future__ import annotations

from zoneinfo import ZoneInfo

import pytest

from src.storage import GCodeStorage


@pytest.fixture
def storage(tmp_path):
  '''Storage with store_gcode=True so .gcode files are kept on disk.'''
  return GCodeStorage(
    str(tmp_path / 'gcode'),
    retention_days=90,
    store_gcode=True,
    tz=ZoneInfo('UTC'),
  )


@pytest.fixture
def storage_json_only(tmp_path):
  '''Storage with store_gcode=False (the production default).'''
  return GCodeStorage(
    str(tmp_path / 'gcode'),
    retention_days=90,
    store_gcode=False,
    tz=ZoneInfo('UTC'),
  )


def make_gcode(
  *,
  input_filename_base: str | None = None,
  filename_format: str | None = None,
  output_filename_format: str | None = None,
  slicer_version: str | None = 'ElegooSlicer 1.3.2.9',
  generated_date: str | None = '2026-03-06 at 19:16:22 UTC',
  per_slot_mm: str | None = None,
  per_slot_cm3: str | None = None,
  per_slot_grams: str | None = None,
  per_slot_cost: str | None = None,
  filament_settings_id: str | None = None,
  total_grams: float | None = None,
  total_cost: float | None = None,
  total_filament_changes: int | None = None,
  total_layers: int | None = None,
  estimated_time: str | None = None,
) -> bytes:
  '''Build a synthetic G-code blob with controllable metadata sections.'''
  header_lines = ['; HEADER_BLOCK_START']
  if slicer_version and generated_date:
    header_lines.append(f'; generated by {slicer_version} on {generated_date}')
  header_lines.append('; HEADER_BLOCK_END')

  body_lines = [
    '; EXECUTABLE_BLOCK_START',
    'G28',
    'G1 X10 Y10 Z0.2 F3000',
    '; EXECUTABLE_BLOCK_END',
  ]

  tail_lines = []
  if per_slot_mm is not None:
    tail_lines.append(f'; filament used [mm] = {per_slot_mm}')
  if per_slot_cm3 is not None:
    tail_lines.append(f'; filament used [cm3] = {per_slot_cm3}')
  if per_slot_grams is not None:
    tail_lines.append(f'; filament used [g] = {per_slot_grams}')
  if per_slot_cost is not None:
    tail_lines.append(f'; filament cost = {per_slot_cost}')
  if total_grams is not None:
    tail_lines.append(f'; total filament used [g] = {total_grams}')
  if total_cost is not None:
    tail_lines.append(f'; total filament cost = {total_cost}')
  if total_filament_changes is not None:
    tail_lines.append(f'; total filament change = {total_filament_changes}')
  if total_layers is not None:
    tail_lines.append(f'; total layers count = {total_layers}')
  if estimated_time is not None:
    tail_lines.append(f'; estimated printing time = {estimated_time}')

  config_lines = ['; CONFIG_BLOCK_START']
  if input_filename_base is not None:
    config_lines.append(f'; input_filename_base = {input_filename_base}')
  if filename_format is not None:
    config_lines.append(f'; filename_format = {filename_format}')
  if output_filename_format is not None:
    config_lines.append(f'; output_filename_format = {output_filename_format}')
  if filament_settings_id is not None:
    config_lines.append(f'; filament_settings_id = {filament_settings_id}')
  config_lines.append('; CONFIG_BLOCK_END')

  all_lines = header_lines + body_lines + tail_lines + config_lines
  return '\n'.join(all_lines).encode('utf-8')
